version: '3'

volumes:
    pg_data:

services:
    postgres_db:
        image: postgres:12.2
        volumes:
            - pg_data:/var/lib/postgresql
        environment:
            - POSTGRES_DB=api
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        ports:
            - 25432:5432
        restart: on-failure
        healthcheck:
            test: exit 0

    go_backend:
        build: ./
        environment:
            - DB_NAME=api
            - DB_USER=docker
            - DB_PASS=docker
            - DB_HOST=postgres_db
        ports:
            - 4000:4000
        restart: on-failure
        depends_on:
            - postgres_db
        command: go run main.go
